--- #YAML:1.0
name:                CGI-Application-Plugin-Flash
version:             0.01
abstract:            Flash ...
license:             ~
author:              
    - Bradley C Bailey <cap-flash@brad.memoryleak.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI::Application:              4
    CGI::Application::Plugin::Session: 1
    CGI::Session::Flash:           0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
